name: luoyi_flutter_font
description: "flutter dynamic load font, optimize chinese font render effect"
version: 1.0.11
homepage: https://github.com/luoyi58624/luoyi_flutter_font

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  localstorage: ^5.0.0
  luoyi_dart_base: ^1.9.0
  path_provider: ^2.1.3
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
